config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'profiles/show'

  get 'all', to: 'posts#browse', as: :browse_posts

  devise_for :users

  resources :posts do 
    resources :comments, only: [:create, :destroy]
     member do
      get 'like'
      get 'dislike'
    end
  end

  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable

	belongs_to :user
	has_many :comments, dependent: :destroy
	
	validates :image, presence: true
  
	has_attached_file :image,
                    styles: { medium: '640x'}

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  scope :of_followed_users, -> (following_users) { where user_id: following_users }
  
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_voter

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
				 :validatable

  validates :username, presence: true, length: { maximum: 20 }

  has_attached_file :avatar, styles: { medium: '152x152#' }
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :fetch_post

	def create
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id

	  if @comment.save
	    flash[:success] = "You commented the hell out of that post!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end

	def destroy
	  @comment = @post.comments.find(params[:id])

	  @comment.destroy
	  flash[:success] = "Comment deleted"
	  redirect_to root_path
	end

	private
	
	def fetch_post
  	@post = Post.find(params[:post_id])
	end

	def comment_params
  	params.require(:comment).permit(:content)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :fetch_post, only: [:show, :edit, :update, :destroy, :like, :dislike]

	def index
		@posts = Post.of_followed_users(current_user.following).order('created_at DESC')
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = 'Your post has been created!'
			redirect_to root_path
		else
			flash.now[:alert] = 'Your new post couldn\'t be created!  Please check the form.'
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = 'Post updated.'
	  	redirect_to @post
	  else
	  	flash.now[:alert] = 'Update failed.  Please check the form.'
	  	render 'edit'
	  end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like
	  if @post.liked_by current_user
	     redirect_to root_path
	  end
	end

	def dislike
		if @post.unliked_by current_user
			redirect_to root_path
		end
	end

	def browse
	  @posts = Post.all.order('created_at DESC')
	end


	private
	
	def fetch_post
	  @post = Post.find(params[:id])
	end

	def post_params
  	params.require(:post).permit(:image, :caption, :user_id)
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
  before_action :fetch_user, only: [:show, :edit, :update, :owned_profile]
  before_action :owned_profile, only: [:edit, :update]
  
  def show
  	  @posts = User.find_by(username: params[:username]).posts.order('created_at DESC')

  	  #@posts = User.find(params[:id]).posts.order('created_at DESC')
  end

	def edit
	end

	def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.username)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render 'edit'
    end
  end

	private

	def fetch_user
		@user = User.find_by(username: params[:username])
	end
	
	def profile_params
  	params.require(:user).permit(:avatar, :bio)
	end

	def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # before_action :fetch_user

  def follow_user
  	@user = User.find_by! username: params[:username]
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow_user
  	@user = User.find_by! username: params[:username]
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include PostsHelper
	include ProfilesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def alert_for(flash_type)
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
	end

	def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
	def profile_avatar_select(user)
	  return image_tag user.avatar.url(:medium),
	                   id: 'image-preview',
	                   class: 'img-responsive img-circle profile-image' if user.avatar.exists?
	  image_tag 'default-avatar.jpg', id: 'image-preview',
     	                             class: 'img-responsive img-circle profile-image'
	end

	def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Instagram</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to "Profile", profile_path(current_user.username), class: 'btn btn-default navbar-btn' %>
       	  <%= link_to "New post", new_post_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to "All posts", browse_posts_path, class: 'btn btn-default navbar-btn' %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.username,  edit_user_registration_path, class: 'navbar-link' %>
          </p>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-default', data: {confirm: "Do you really want to leave?"} %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="posts-wrapper row">
  <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)]  %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
	<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|%>
	  <div class="form-group text-center">
	  	<%= f.input :image %>
	  </div>
	  
	  <div class="form-group text-center">
	  	<%= f.input :caption %>
	  </div>
	  
	  <div class="form-group text-center">
	  	<%= f.button :submit %>
	  </div>

	  <%= f.hidden_field :user_id, value: current_user.id %>
	<% end %>
</div>

app/views/posts/browse.html.erb
<div class="posts-wrapper row">
	<%= render 'shared/post' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
  <%= render 'form' %>

<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path, class: 'btn btn-success' %>
</div>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
	<% if !@posts.empty? %>
		<%= render 'shared/post' %>
	<% else %>
		<h1>Your tape is empty. <br>Subscribe to someone</h1>
		<%= link_to "See all posts", browse_posts_path, class: 'btn btn-primary navbar-btn' %>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>Add new post</h1>
<div class="form-wrapper">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
	<div class="post">
		<div class="post-head">
			<div class="name">
				<%= link_to @post.user.username, profile_path(@post.user.username) %>
			</div>
		</div>
		<div class="image center-block">
			<%= image_tag @post.image.url(:medium) %>
		</div>
		<p class="caption"><%= @post.caption %></p>
		<div class="text-center">
			
			<%= link_to '', like_post_path(@post.id), id: "like_#{@post.id}", class: "glyphicon glyphicon-heart-empty" unless current_user.voted_for? @post %>
				<%= link_to '', dislike_post_path(@post.id), id: "like_#{@post.id}", class: "glyphicon glyphicon-heart" if current_user.voted_for? @post %>
				<span class="label label-info" id="like_size"><%= @post.votes_for.size %></span>

			<% if @post.user.id == current_user.id %>
				<%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-success' %>
				<%= link_to 'Delete Post', post_path(@post), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
			<% end %>
			<%= link_to 'Cancel', posts_path, class: 'btn btn-default' %>
		</div>
	</div>
	<%= render 'shared/comment' %>
</div>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4> Change your profile image: </h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4> Update your bio: </h4>
                  <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
     </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
         	<%= @user.username %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.username), class: 'btn edit-button' %>
          <% elsif current_user_is_following(current_user.id, @user.id) %>
      			<%= link_to 'Following', unfollow_user_path, class: 'btn btn-success', method: :post %>
          <% else %>
            <%= link_to 'Follow', follow_user_path, class: 'btn btn-success', method: :post %>
         	<% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="posts-wrapper row">
	<%= render 'shared/post' %>
</div>

app/views/relationships/follow_user.html.erb
<h1>Relationships#follow_user</h1>
<p>Find me in app/views/relationships/follow_user.html.erb</p>

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>

app/views/shared/_comment.html.erb
<% @post.comments.each do |comment| %>
  <div class="panel panel-primary">
  	<div class="panel-heading">
			<%= comment.user.username %>
			<%= link_to 'Delete', post_comment_path(@post,comment), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure?"} if comment.user.id == current_user.id %>
		</div>
		<div class="panel-body">
			<%= comment.content %>
		</div>
	</div>
<% end %>
<div class="row">
	<div class="col-sm-12">
		<%= form_for [@post, @post.comments.new], html: { class: 'form-horizontal' } do |f|%>
		  <div class="form-group text-center">
		  	<%= f.text_area :content, placeholder: 'Add a comment...' %>
		  </div>
		  
		  <div class="form-group text-center">
		  	<%= f.button :submit %>
		  </div>
		<% end %>
	</div>
</div>

app/views/shared/_post.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<div class="post-head">
			<div class="name">
				<%= link_to post.user.username, profile_path(post.user.username) %>
			</div>
		</div>
		<div class="image center-block">
			<%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %> <br>
		</div>
		<p class="caption">
			<%= link_to '', like_post_path(post.id), id: "like_#{post.id}", class: "glyphicon glyphicon-heart-empty" unless current_user.voted_for? post %>
			<%= link_to '', dislike_post_path(post.id), id: "like_#{post.id}", class: "glyphicon glyphicon-heart" if current_user.voted_for? post %>
			<span class="label label-info" id="like_size"><%= post.votes_for.size %></span>
		</a>
			<%= post.caption %>
		</p>
	</div>
<% end %>